### PR TITLE
Deserializing value should not hold the TaskSchedulerImpl lock

### PR DESCRIPTION
**Pull request by markhamstra**
SKIPME

Backport of some of the SPARK-7655 fix.

### CODE REVIEW

**Comment by mbautin** [comment]
LGTM

**Comment by jlagerblad** [comment]
@markhamstra and @mbautin; To me the fix looks a bit suspicious from a multi threading perspective. In Java; I would use volatile at least for the boolean flag - I assume that's the same as @volatile. 

But since I don't know how the code is used; it might not be required....

**Comment by markhamstra** [comment]
Looks to me that you are correct.  Good catch!  I'll re-open the discussion
of the PR against Apache Spark.

**Comment by markhamstra** [comment]
Shixiong Zhu cleared it up for me: It's okay as it is since the first call
to value() occurs within the same thread as the second (the one that is
synchronized on TaskSchedulerImpl), so no @volatile is needed.

**Pull request merged**
