### PR TITLE
Log JobGroup

### PR DESCRIPTION
**Pull request by markhamstra**
REL-627

### CODE REVIEW

**Comment by vnivargi** [comment]
build stuck?

**Comment by markhamstra** [comment]
Looks like it, but it wouldn't surprise me if we can't get Jenkins to test Spark successfully right now.  The 1.2 has some testing issues that are much better on 1.3, but even testing locally it can take me multiple attempts to get through all of the tests piecemeal.

**Comment by vnivargi** [comment]
build hasn't failed though. where is it stuck?

**Comment by markhamstra** [comment]
I'm not sure where Jenkins is getting hung up.  The current attempt (#90) looks to be stuck at the same point where I killed off the prior attempt (#89), but it also appears that not all of the test console output ends up in the Jenkins console output, so I can't really see what is currently running.  We may need to change our Jenkins to use something more like what the AMPlab jenkins uses (https://github.com/apache/spark/blob/master/dev/run-tests-jenkins) instead of running tests via maven.  The Apache run-tests scripts are by no means trouble-free, but I think they are more stable or at least better exercised than running the tests through maven.

**Comment by vnivargi** [comment]
have you tried running the tests locally like jenkins does? the jenkins runs will also be present locally on the slave where the tests are running if you want to confirm if there is a discrepancy between console output and jenkins log output. should be possible to resolve where jenkins is getting stuck.

**Comment by markhamstra** [comment]
I'm going to merge this since it is just a (very useful) logging message change, the rest of spark-1.2.2-csd-1 has been working well and is passing local tests as well as do Apache Spark 1.2.2 and 1.2.1-csd-4.

I'll deal with Jenkins later.

**Pull request merged**
