### PR TITLE
SPY-1037: sizing the #slices used in parallelize() call of ParquetRelation#mergeSchemasInParallel

### PR DESCRIPTION
**Pull request by ianlcsd**
@markhamstra 
@davidnavas

### CODE REVIEW

**Comment by ianlcsd** [comment]
I think we can further narrow the parallelism calculation to none s3 Path. 
```
    // Use the first file as an indicator to see if we are dealing with s3.
    // if it is on s3, use the defaultParallelism from sparkContext,
    // otherwise we size it properly.
    val parallelism = partialFileStatusInfo.headOption.filter(!_._1.startsWith("s3")).map( _ =>
      math.min(
        math.max(1, partialFileStatusInfo.length),
        sqlContext.sparkContext.defaultParallelism)
    ).getOrElse(sqlContext.sparkContext.defaultParallelism)
```

**Comment by markhamstra** [comment]
I'm concerned about what happens when defaultParallelism is not set and we are dealing with s3.  Then we will launch as many Tasks as we have cores, which has the potential to tie up many, even all, cores for the duration of a read from s3.  I don't think we want to risk blocking other Jobs in that way.

**Comment by ianlcsd** [comment]
The current s3 optimization is too extreme.
Should we introduce a new parameter for that? Did we introduce our own configuration to csd-spark?

**Comment by markhamstra** [comment]
That's kind of what I am thinking, that a different config variable than sparkContext.defaultParallelism may be needed for this default, one more specific or maybe exclusive to reading parquet schemas.

**Comment by ianlcsd** [comment]
the parquet specific config property naming from http://spark.apache.org/docs/latest/sql-programming-guide.html is suggesting something like "spark.sql.parquet.*"
I am thinking about spark.sql.parquet.mergeSchema.parallelism!

**Comment by ianlcsd** [comment]
jttp

**Pull request merged**
