### PR TITLE
SPY-1281: packaging spark-<version>-yarn-shuffle.jar under /usr/share/spark/yarn_lib

### PR DESCRIPTION
**Pull request by ianlcsd**
@markhamstra 
@davidnavas 
@yeweizhang

### CODE REVIEW

**Comment by davidnavas** [comment]
"Could not resolve dependencies for project
org.apache.spark:spark-streaming-kafka-assembly_2.11:jar:1.6.3-csd-3-SNAPSHOT:
The following artifacts could not be resolved:
org.apache.spark:spark-streaming-kafka_2.10:jar:1.6.3-csd-3-SNAPSHOT,
org.apache.spark:spark-streaming_2.10:jar:1.6.3-csd-3-SNAPSHOT: Failure to
find org.apache.spark:spark-streaming-kafka_2.10:jar:1.6.3-csd-3-SNAPSHOT
in http://maven.clearstorydatainc.com/content/groups/public was cached in
the local repository, resolution will not be reattempted until the update
interval of nexus has elapsed or updates are forced -> [Help 1]"

**Comment by ianlcsd** [comment]
the PR builds are failing the same way now.

**Comment by markhamstra** [comment]
Yeah, the PR builder doesn't work for Spark.  I'll take a look at this this afternoon and make sure things are building correctly before merging and doing a new release. The packaging of the additional jars looks reasonable.

**Comment by zbelzer** [comment]
Pretty please build a docker image for it too! Instructions are in Dockerfile.

**Comment by markhamstra** [comment]
There is no Dockerfile.  If you want that PR merged, then you can do that.  If you want a docker image built with every release, then the way to do that is not to beg people to remember to do additional steps, but rather to add the necessary build-image-and-upload commands to the Jenkins release builder -- just append to the "Execute shell" in the "Build" section. http://jenkins.clearstorydata.com/view/spark/job/spark.release/configure

**Comment by zbelzer** [comment]
Wouldn't have hurt to give me explicit permission to merge the PR in the first place
https://github.com/clearstorydata/spark/pull/177. I have no problem automating these things.

**Pull request merged**
