### PR TITLE
SKIPME expose the parquet util to be public to be used by csd persist…

### PR DESCRIPTION
**Pull request by wli600**
replacing the one on master, https://github.com/clearstorydata/spark/pull/70

@davidnavas @markhamstra 

was able to run the test unit with the snapshot build with corresponding changes

### CODE REVIEW

**Comment by davidnavas** [comment]
Seems reasonable -- why all the failures though?

**Comment by wli600** [comment]
jenkins, test this please

**Comment by markhamstra** [comment]
I wouldn't expect Jenkins to be able to run the Spark tests consistently.  There are some known flakey tests and some differences between how our Jenkins runs the tests vs. how the canonical AMPLab Jenkins does.  I'll run them locally and see if there is anything to be concerned over.

**Comment by wli600** [comment]
sweet, thanks, Mark, yeah, these changes should not be harmful from the
look of it,

meanwhile, I think I just kicked off a jenkins job,  finger crossed,

On Wed, Jul 29, 2015 at 9:41 AM, Mark Hamstra <notifications@github.com>
wrote:

> I wouldn't expect Jenkins to be able to run the Spark tests consistently.
> There are some known flakey tests and some differences between how our
> Jenkins runs the tests vs. how the canonical AMPLab Jenkins does. I'll run
> them locally and see if there is anything to be concerned over.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clearstorydata/spark/pull/71#issuecomment-126012720>.
>



-- 
- Wei

**Comment by wli600** [comment]
replaced with proper branch, https://github.com/clearstorydata/spark/pull/73

**Pull request closed without merging**
